services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=test'
      - 'MYSQL_ROOT_PASSWORD=test'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - ./data:/var/lib/mysql
  myapp:
      build: . 
      ports:
        - '8080:8080'
      environment:
        - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase'
        - 'SPRING_DATASOURCE_USERNAME=myuser'
        - 'SPRING_DATASOURCE_PASSWORD=test'
      depends_on:
        mysql:
          condition: service_healthy